# Generated by Django 2.1.5 on 2020-06-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('small', models.CharField(max_length=64)),
                ('large', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
