# Generated by Django 2.1.5 on 2020-06-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_dinner_pasta_salads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasta_salads',
            name='price',
            field=models.CharField(max_length=64),
        ),
    ]
