# Generated by Django 2.1.5 on 2020-06-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200608_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasta_salads',
            old_name='name',
            new_name='n',
        ),
    ]
