# Generated by Django 2.1.5 on 2020-06-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200614_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasta_salads',
            old_name='n',
            new_name='name',
        ),
    ]
