# Generated by Django 2.1.5 on 2020-06-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200614_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('topping', models.CharField(max_length=64)),
                ('subs', models.CharField(max_length=64)),
            ],
        ),
    ]
