# Generated by Django 2.1.5 on 2020-06-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='subs',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
