# Generated by Django 2.1.5 on 2020-06-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200617_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='second_topping',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='third_topping',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='type',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
    ]
