# Generated by Django 2.1.5 on 2020-06-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200619_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='subs',
        ),
    ]
