# Generated by Django 2.1.5 on 2020-06-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orders_subs'),
    ]

    operations = [
        migrations.AddField(
            model_name='regular',
            name='type',
            field=models.CharField(default='Regular', max_length=64),
        ),
        migrations.AddField(
            model_name='sicilian',
            name='type',
            field=models.CharField(default='Sicilian', max_length=64),
        ),
    ]
