# Generated by Django 2.1.5 on 2020-06-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pasta_salads',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='pasta_salads',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
