# Generated by Django 2.1.5 on 2020-06-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200622_1053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='plate',
            new_name='plat',
        ),
    ]
