# Generated by Django 2.1.5 on 2020-06-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200622_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='plat',
            new_name='plate',
        ),
    ]
