# Generated by Django 2.1.5 on 2020-06-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200622_1206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='carts',
        ),
    ]
