# Generated by Django 2.1.5 on 2020-06-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200622_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='topping',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='topping',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
