# Generated by Django 2.1.5 on 2020-06-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20200624_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
