# Generated by Django 2.1.5 on 2020-06-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20200626_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='large',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='small',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='large',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='small',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subs',
            name='large',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subs',
            name='small',
            field=models.IntegerField(),
        ),
    ]
