# Generated by Django 2.1.5 on 2020-06-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20200626_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pasta_salads',
            name='price',
            field=models.IntegerField(),
        ),
    ]
