# Generated by Django 2.1.5 on 2020-06-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20200626_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pizza',
            new_name='item',
        ),
        migrations.DeleteModel(
            name='dinner',
        ),
        migrations.DeleteModel(
            name='subs',
        ),
        migrations.RenameField(
            model_name='pasta_salads',
            old_name='price',
            new_name='large',
        ),
    ]
