# Generated by Django 2.1.5 on 2020-06-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20200626_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='small',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pasta_salads',
            name='large',
            field=models.FloatField(),
        ),
    ]
