# Generated by Django 2.1.5 on 2020-06-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20200626_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasta_salads',
            old_name='large',
            new_name='price',
        ),
    ]
