# Generated by Django 2.1.5 on 2020-06-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20200626_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasta_salads',
            old_name='name',
            new_name='n',
        ),
    ]
